### ISSUE TITLE
اضافة

### ISSUE THREAD

**Issue by hloljob** [AqeelAT/arabic-apis#3]
بوابة البيانات المفتوحة السعودية
https://data.gov.sa/en/puplishers-apis

منصة واثق تقدم خدمات الربط للمجالات التالية

وزارة التجارة 

السجلات التجارية عبر النفاذ التجاري الموحد
https://developer.wathq.sa/ar/api/19

وزارة التجارة الهوية الاعتبارية
https://developer.wathq.sa/ar/api/11

مجلس الغرف السعودية
خدمة مقدمة من الغرف التجارية تتيح للمستفيدين التحقق من كامل تفاصيل اشتراك السجل في الغرف التجارية

https://developer.wathq.sa/ar/api/15

وزارة التجارة شهادة المنشأ

https://developer.wathq.sa/ar/api/9

وزارة العدل الوكالات العدلية
https://developer.wathq.sa/ar/api/14

وزارة العدل الصكوك العقارية
https://developer.wathq.sa/ar/api/13

وزارة التجارة السجلات التجارية
https://developer.wathq.sa/ar/api/16

**Comment by aqeelat** [comment]
شكرا لك على مشاركتك لهذه المصادر. تمت إضافتها.
