### ISSUE TITLE
اضافة

### ISSUE THREAD

**Issue by hloljob** [AqeelAT/arabic-apis#4]
اداة لتحويل الملفات
https://convertio.co/ar/

دبي الذكية
https://developer.dubai.gov.ae/#default/home

 خدمة رومنة الأسماء الجغرافية
https://www.gasgi.gov.sa/Ar/EService/Pages/Romanization.aspx

مركز البيانات المفتوحة أمانة محافظة جدة يتطلب تسجيل
https://services.jeddah.gov.sa/OpenData/Default.aspx

**Comment by aqeelat** [comment]
شكرا لك. قمت بإضافة جميع الواجهات ما عدا اداة تحويل البيانات. أرجو منك المشاركة في النقاش في #7 لنحدد اذا كان يمكننا اعتبار هذه الواجهة عربية.

**Comment by hloljob** [comment]
بكل تاكيد معك في ماذكرت والافضل انها تكون من اعداد وبرمجة مطور عربي
