### ISSUE TITLE
تحويل عرض الكتابة من اليمين لليسار في ملف الـ README.md 

### ISSUE THREAD

**Issue by AhmedElTabarani** [AqeelAT/arabic-apis#6]
<div dir = rtl>
ارجوا وضع كل محتوى ملف الـ README.md 
في وسم الـ div وتغير الاتجاه dir = rtl

<div dir = ltr>

```
<div dir = rtl>
مرحبًا
</div>
```
</div>

</div>

**Comment by aqeelat** [comment]
<div dir = rtl>
هل يمكنك انشاء fork
ووضع هذا الوسم؟ لانني حاولت ولم استطع جعل الصفحة من اليمين لليسار
</div>

**Comment by aqeelat** [comment]
<div dir=rtl>
خلاص عرفت كيف.
اللي كان حاصل ان preview 
ما كان يطلع تغيير الاتجاه
</div>
